
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 14 21:38:58 EST 2009
//----------------------------------------------------

package com.thedomokun.common;

/** CUP generated class containing symbol constants. */
public class LogoSym {
  /* terminals */
  public static final int FR = 19;
  public static final int PLUS = 12;
  public static final int FL = 20;
  public static final int IDENTIFIER = 18;
  public static final int END = 8;
  public static final int COLON = 23;
  public static final int LBRACKET = 16;
  public static final int RBRACKET = 17;
  public static final int BACKWARD = 3;
  public static final int RIGHT = 4;
  public static final int FORWARD = 2;
  public static final int LEFT = 5;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int MULT = 15;
  public static final int DIV = 14;
  public static final int MINUS = 13;
  public static final int BR = 21;
  public static final int error = 1;
  public static final int INTEGER = 9;
  public static final int BL = 22;
  public static final int TO = 7;
  public static final int REPEAT = 6;
  public static final int DOUBLE = 11;
  public static final int MAKE = 24;
  public static final int QUOTE = 25;
  public static final int IF = 26;
  public static final int IFELSE = 27;
  public static final int PRINT = 28;
  public static final int SUM = 29;
  public static final int PRODUCT = 30;
  public static final int DIFFERENCE = 31;
  public static final int QUOTIENT = 32;

  public static final int LEQ = 33;
  public static final int LT = 34;
  public static final int GEQ = 35;
  public static final int GT = 36;
  public static final int EQ = 37;

  public static final int OUTPUT = 38;
  public static final int FIRST = 39;
  public static final int LAST = 40;
  public static final int BUTFIRST = 41;
  public static final int BUTLAST = 42;

  public static final int SENTENCE = 43;
  public static final int LIST = 44;
  public static final int ITEM = 45;

  public static final int EQUALP = 46;
  public static final int LESSP = 47;
  public static final int GREATERP = 48;
}

